Removed dependency on sysctl
This system call no longer exists on current kernels. See: https://man7.org/linux/man-pages/man2/sysctl.2.html
Prevents building on fedora 33. Fails with error:
```make: Entering directory '/home/saleemabdulhamid/Employment/Software/Consulting/wave-master/node_modules/netroute/build'
  CXX(target) Release/obj.target/netroute/src/netroute.o
../src/netroute.cc:8:10: fatal error: sys/sysctl.h: No such file or directory
    8 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

Builds and works fine without it.